### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by adryan089** [cmalf/supra-starcade-monitor#1]
Bang ga bikin auto play game supra kah?

**Comment by cmalf** [comment]
belum kelar update(upgrade) tesnet. di pakein bot ga worth it. (error mulu). Besok kalo dah kelar upgrade, kalo ada waktu gw release botnya.

**Comment by adryan089** [comment]
wokey bang siappp ditunggu update an nya bang hehehehe

**Comment by adryan089** [comment]
wokey bang siappp ditunggu update an nya bang hehehehe
